### ISSUE TITLE
Add payoff vector generation

### ISSUE THREAD

**Issue by GeorgeR227** [GeorgeR227/CAP-SMC-Project#1]
The foundation of our project is the payoff vector so we should start by being able to calculate this.

Since we haven't yet decided on specific starting budgets and price for goods, this should just take a list of budgets for each province and a list of prices to utilities and then generate the payoffs for all coalitions. Note that the examples we worked on were basic and this calculation may need some more complicated algorithm.

**Comment by Dan2k03** [comment]
Currently only prints out the payoff vectors for each different combination. Very easy change to store the payoffs whenever we need to.

**Comment by GeorgeR227** [comment]
Closed by PR #13.
